version: "3.9"

services:
    app_backend:
        container_name: ${APP_CONTAINER_NAME}
        hostname: ${APP_HOSTNAME}
        restart: always
        working_dir: ${SRC_PATH}
        build:
            context: .
            dockerfile: php/development/Dockerfile
            args:
                - "UID"
                - "GID"
                - "USER_NAME"
                - "SRC_PATH"
        environment:
            UID: ${UID}
            GID: ${GID}
            USER_NAME: ${USER_NAME}
            RDMS_DB_NAME: ${RDMS_DB_NAME}
            RDMS_DB_PASSWORD: ${RDMS_DB_PASSWORD}
            RDMS_DB_USER: ${RDMS_DB_USER}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - database
        volumes:
            - ../app:${SRC_PATH}
            - ./php/development/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./php/development/date.ini:/usr/local/etc/php/conf.d/date.ini
            - ./php/development/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    nginx:
        container_name: ${NGINX_CONTAINER_NAME}
        hostname: ${NGINX_HOSTNAME}
        build:
            context: .
            dockerfile: nginx/Dockerfile
            args:
                - "DOMAIN"
                - "SRC_PATH"
                - "PUBLIC_PATH"
        depends_on:
            - app_backend
        volumes:
            - ../app:${SRC_PATH}
        ports:
            - "80:80"

    database:
        container_name: ${RDMS_CONTAINER_NAME}
        hostname: ${RDMS_HOSTNAME}
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: ${RDMS_DB_NAME}
            POSTGRES_PASSWORD: ${RDMS_DB_PASSWORD}
            POSTGRES_USER: ${RDMS_DB_USER}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${RDMS_DB_NAME}", "-U", "${RDMS_DB_USER}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin4:
        container_name: ${PGADMIN_CONTAINER_NAME}
        image: dpage/pgadmin4:7
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 8080
        ports:
            - "8080:8080"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - database

    rabbitmq:
        container_name: ${RABBITMQ_CONTAINER_NAME}
        image: rabbitmq:3.9-management
        ports:
            - "5672:5672"  # AMQP protocol
            - "15672:15672" # Management UI
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq # Optional: for data persistence
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    s3:
        container_name: ${MINIO_CONTAINER_NAME}
        image: minio/minio:latest
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio:/data
        command: server /data --console-address ":9001"
        networks:
            local:

volumes:
    postgres_data:
    pgadmin_data:
    minio:
    rabbitmq_data:

networks:
    local:
        driver: bridge
